# Generated by Django 3.1 on 2020-12-11 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreponse',
            name='id_question',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='id_reponse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='id_test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='poids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='reponse_correctes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 16, 20, 16, 958855)),
        ),
    ]
