# Generated by Django 3.1 on 2020-12-11 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_auto_20201211_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 16, 43, 20, 301989)),
        ),
    ]
