# Generated by Django 3.1 on 2020-12-15 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_auto_20201211_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionreponse',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='questionreponse',
            name='id_reponse',
        ),
        migrations.RemoveField(
            model_name='questionreponse',
            name='id_test',
        ),
        migrations.AddField(
            model_name='question',
            name='code_question',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='code_question',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='code_reponse',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='code_test',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='code_reponse',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='code_test',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 14, 33, 15, 216912)),
        ),
    ]
